#version: "3"
services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "femr_db"
      MYSQL_USER: "femr"
      MYSQL_PASSWORD: "__PASSWORD__"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql

  femr:
    platform: linux/amd64
    image: djump13/test-image:latest
    links:
      - db:mysql
    depends_on:
      - db
    entrypoint: sbt start -Dhttps.port=9443 -Dpidfile.path=/dev/null
    tty: true
    ports:
      - "80:9000"
      - "433:9443"
    expose:
      - "9000"
      - "9443"

    volumes:
      - ./femr/conf:/usr/src/app/conf
  dns:
    restart: always
    image: strm/dnsmasq
    volumes:
      - ./dns.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
    expose:
      - "53"
    cap_add:
      - NET_ADMIN

volumes:
  db-data: