version: "3"
services:

  db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'femr_db'
      MYSQL_USER: 'femr'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command:
      - "mysqld"
      - "--log-bin-trust-function-creators=1"
    volumes:
      - db-data:/var/lib/mysql

  femr:
    build: .
    links: 
      - db:mysql
    depends_on: 
      - db
    tty: true
    ports:
      - '9000:9000'

    environment:
      DB_URL: 'jdbc:mysql://db:3306/femr_db?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true'
      DB_USER: 'femr'
      DB_PASS: 'password'

    volumes:
      - ./speedtest:/usr/src/speedtest


volumes:
  db-data:
