version: "3"
services:

  db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'femr_db'
      MYSQL_USER: 'femr'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command:
      - "mysqld"
      - "--log-bin-trust-function-creators=1"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  femr:
    build: .
    links: 
      - db:mysql
    depends_on: 
      db:
        condition: service_healthy
    tty: true
    restart: on-failure:10
    expose:
      - "9000"

    environment:
      DB_URL: 'jdbc:mysql://db:3306/femr_db?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true'
      DB_USER: 'femr'
      DB_PASS: 'password'
      IS_DOCKER: 'true'

    volumes:
      - ./speedtest:/usr/src/speedtest

  caddy:
    depends_on:
      - femr
    image: caddy:latest
    container_name: caddy-https

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db-data:
  caddy_data:
  caddy_config: