#!/bin/bash
# Ad Hoc Set Up 

sudo ifconfig wlan0 down
sudo iwconfig wlan0 mode ad-hoc
sudo iwconfig wlan0 essid 'fEMR'
sudo iwconfig wlan0 key off
sudo ifconfig wlan0 10.42.0.1
echo "Ad Hoc Complete"
