name: Docker Image CI/CD

on:
  push:

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_EMAIL }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker Dependencies
        uses: actions/cache@v3
        with:
          path: |
            root/.ivy2
            root/.sbt
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt', '**/project/*.sbt') }}
          restore-keys: |
            sbt-${{ runner.os }}-

      - name: Inject sbt cache into Docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "root/.ivy2": "/root/.ivy2",
              "root/.sbt": "/root/.sbt"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Build and Push Docker Image to Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: teamfemrdev/teamfemr:latest
