name: Generate Installer and Dispatch On Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: "Release version"
        required: true
        default: "0.0.0"

jobs:
  build_and_push_image:
    name: Build and Push Image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_EMAIL }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Caches dependencies separately for each platform.
      - name: Cache Docker Dependencies
        uses: actions/cache@v3
        with:
          path: |
            root/.ivy2
            root/.sbt
          key: sbt-${{ runner.os }}-${{ hashFiles('**/build.sbt', '**/project/*.sbt') }}
          restore-keys: |
            sbt-${{ runner.os }}

      # Injects the cache into the Docker build. Path is based on cache path in Dockerfile.
      - name: Inject sbt cache into Docker
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "root/.ivy2": "/root/.ivy2",
              "root/.sbt": "/root/.sbt"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Strip leading 'v' from tag # Or uses the input from workflow dispatch if not a release
        id: tag
        run: |
          RAW_TAG="${{ github.event.release.tag_name }}"
          if [ -z "$RAW_TAG" ]; then
            RAW_TAG="${{ github.event.inputs.release }}"
          fi
          STRIPPED_TAG="${RAW_TAG#v}"
          echo "stripped_tag=$STRIPPED_TAG" >> $GITHUB_OUTPUT

      - name: Set current date as env var
        run: echo "DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        env:
          DATE: ${{ env.DATE }}
        with:
          context: .
          platforms: linux/amd64, linux/arm64 #Platforms to build image for.
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            APP_VERSION=${{ steps.tag.outputs.stripped_tag}}
            BUILD_DATE=${{ env.DATE }}
          push: true
          tags: teamfemrdev/teamfemr:latest

  # This job sends a repository dispatch event to the installer repository to generate an installer
  # and upload it to s3 when a release is published.
  send_dispatch:
    name: Send Dispatch
    needs: build_and_push_image
    runs-on: ubuntu-latest
    steps:
      - name: Strip leading 'v' from tag # Or uses the input from workflow dispatch if not a release
        id: tag
        run: |
          RAW_TAG="${{ github.event.release.tag_name }}"
          if [ -z "$RAW_TAG" ]; then
            RAW_TAG="${{ github.event.inputs.release }}"
          fi
          STRIPPED_TAG="${RAW_TAG#v}"
          echo "stripped_tag=$STRIPPED_TAG" >> $GITHUB_OUTPUT
      - name: Send Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: FEMR/installer-femr
          event-type: generate-installer
          client-payload: '{"release": "${{ steps.tag.outputs.stripped_tag }}"}'
